# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeLs < Formula
  desc "Terminal UI for managing Claude Code sessions"
  homepage "https://github.com/alexmt/claude-ls"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexmt/claude-ls/releases/download/v0.1.0/claude-ls_darwin_amd64.tar.gz"
      sha256 "5d66725c0b66ec2d452b72bcfbb9e231e1c3160e2bce41d6856d7c8173cb9f73"

      define_method(:install) do
        bin.install "claude-ls"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexmt/claude-ls/releases/download/v0.1.0/claude-ls_darwin_arm64.tar.gz"
      sha256 "48c7a71b8b6b653d5ade4a40015c671757025b6bfb7112a163e7a254b90f3963"

      define_method(:install) do
        bin.install "claude-ls"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexmt/claude-ls/releases/download/v0.1.0/claude-ls_linux_amd64.tar.gz"
      sha256 "7f2bf8d8dbcfad5f92f8dd3a24d44dc134ae7ddd401bd3dd94adc7ceec2674ec"
      define_method(:install) do
        bin.install "claude-ls"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexmt/claude-ls/releases/download/v0.1.0/claude-ls_linux_arm64.tar.gz"
      sha256 "85a4c666b3f42b191d6060b0895faefa954691b7134a6cee6ca0c7060e24a591"
      define_method(:install) do
        bin.install "claude-ls"
      end
    end
  end
end
