# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeLs < Formula
  desc "Terminal UI for managing Claude Code sessions"
  homepage "https://github.com/alexmt/claude-ls"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexmt/claude-ls/releases/download/v0.2.0/claude-ls_darwin_amd64.tar.gz"
      sha256 "8594fbdd05f848fd80b374c992cb4c5340122b44a65ea284f3c3a49ba4608627"

      define_method(:install) do
        bin.install "claude-ls"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexmt/claude-ls/releases/download/v0.2.0/claude-ls_darwin_arm64.tar.gz"
      sha256 "40bbc74c84cd8586034b7acd29db5905f9390ca1246082c36352493d6f1fbebc"

      define_method(:install) do
        bin.install "claude-ls"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexmt/claude-ls/releases/download/v0.2.0/claude-ls_linux_amd64.tar.gz"
      sha256 "c1b92dee12a8629f2ef3f651cf630b8768884415259c43e5efa1a91e0680a312"
      define_method(:install) do
        bin.install "claude-ls"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexmt/claude-ls/releases/download/v0.2.0/claude-ls_linux_arm64.tar.gz"
      sha256 "29411d7746e302e84943f203f02ebfbc0cbb5daa6a6e01d5dcab9a013ba53b17"
      define_method(:install) do
        bin.install "claude-ls"
      end
    end
  end
end
