# This file was generated by GoReleaser. DO NOT EDIT.
cask "pg-mask-proxy" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "4e5e06c4c759f76b800862b01181ca0b3b8a323a4baf23db9dd3f8df35566d1c"
      url "https://github.com/alexmt/pg-mask-proxy/releases/download/v#{version}/pg-mask-proxy_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "644d1a13f521c8425d50b583a74ce2134e9847a850aadce0788ca9608c336237"
      url "https://github.com/alexmt/pg-mask-proxy/releases/download/v#{version}/pg-mask-proxy_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "757dec21c5641163174fead437a125eb4ad73a055a5776b856bc65361f6926e6"
      url "https://github.com/alexmt/pg-mask-proxy/releases/download/v#{version}/pg-mask-proxy_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7f65cde283cac6101a1a41cd50850e054c10bafb476aa241c98f87fd2bbaf307"
      url "https://github.com/alexmt/pg-mask-proxy/releases/download/v#{version}/pg-mask-proxy_linux_arm64.tar.gz"
    end
  end

  name "pg-mask-proxy"
  desc "PostgreSQL proxy that masks sensitive columns in query results"
  homepage "https://github.com/alexmt/pg-mask-proxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pg-mask-proxy"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pg-mask-proxy"]
  end

  # No zap stanza required

end
